version: 2

models:
  - name: dim_channels
    description: "Dimensions describing Telegram channels"
    columns:
      - name: channel_key
        description: "Surrogate key"
        tests:
          - not_null
          - unique
      - name: channel_name
        description: "Normalized channel name"
  - name: dim_dates
    description: "Calendar dimension for temporal analysis"
    columns:
      - name: date_key
        tests:
          - not_null
          - unique
      - name: full_date
        description: "Date literal"
  - name: fct_messages
    description: "Fact table at message grain"
    columns:
      - name: message_id
        tests:
          - not_null
          - unique
      - name: channel_key
        tests:
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        tests:
          - relationships:
              to: ref('dim_dates')
              field: date_key
  - name: fct_image_detections
    description: "YOLO detections joined to the message fact"
    columns:
      - name: message_id
        tests:
          - relationships:
              to: ref('fct_messages')
              field: message_id
      - name: detected_class
        description: "YOLO label"
